### ISSUE TITLE
Change bar direction to downward for negative value 

### ISSUE THREAD

**Issue by kuntalbose** [chriskmnds/d3-dynamic-grouped-bar-chart#1]
This is not an issue but I not find a better place to post .I try with your code which is works fine with positive values but negative values the bar not appears like I try with bellow data

var chartData = [ {name: 'Foo', value: [{"a":-100}, {"b":150}, {"c":200}]}, 
				  {name: 'Bar', value: [{"a":200}, {"b":-250}, {"c":300}]}, 
				  {name: 'Baz', value: [{"a":300}, {"b":350}, {"c":-400}]} ];	
how to fix this ? a sample is appreciated .I try with http://stackoverflow.com/a/16582072/4336330  but not working .

**Comment by chriskmnds** [comment]
Hi @kuntal-b - thanks for using the code. I really wrote this to work with positive values at the time, as in the examples provided. I will make an effort to refactor/extend it once I get some free time in my hands.

Please feel free to contribute if you've managed to work it out btw.

**Comment by kuntalbose** [comment]
Thankx for reply.I am very new with this library ,and I dnt have much time to learn .I googled it and post here if find something .
